[package]
name = "db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bigdecimal = { workspace = true }
chrono = { workspace = true }
diesel = { workspace = true, features = ["chrono", "numeric", "postgres"] }
diesel-derive-enum = { version = "2.0.1", features = ["postgres"] }
dotenvy = { workspace = true }
envy = { workspace = true }
serde = { workspace = true, features = ["derive"] }
sqlx = { workspace = true, features = ["macros"] }
thiserror = { workspace = true }
types = { path = "../types" }
