[package]
name = "db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bigdecimal = { workspace = true }
chrono = { workspace = true }
diesel = { version = "2.0.4", features = ["chrono", "numeric", "postgres"] }
diesel-derive-enum = { version = "2.0.1", features = ["postgres"] }
dotenvy = { workspace = true, optional = true }
envy = { workspace = true, optional = true }
field_count = "0.1.1"
serde = { workspace = true, optional = true }
sqlx = { workspace = true, optional = true }
thiserror = { workspace = true }
types = { path = "../types" }

[features]
config-loader = ["dep:serde", "dotenvy", "envy"]
sqlx = ["dep:sqlx"]
