[tool.poetry]
name = "econia-sql-formatter"
version = "1.0.0"
description = "Econia SQL formatter"
authors = ["Econia Labs"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
sqlfluff = "^2.0.0"