[workspace]
members = ["api", "db", "types"]
exclude = ["dependencies", "sdk"]

[workspace.dependencies]
bigdecimal = { version = "0.3.0", features = ["serde"] }
chrono = { version = "0.4.24", features = ["serde"] }
diesel = "2.0.2"
dotenvy = "0.15.6"
envy = "0.4.2"
futures-util = "0.3.26"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
sqlx = "0.6.2"
thiserror = "1.0.38"
tokio = { version = "1.25.0", features = ["full"] }
