version: '3.9'
services:

  aptos-builder:
    build:
      context: ../../
      dockerfile: src/docker/aptos-builder/Dockerfile
    image: aptos-builder

  chain:
    build:
      context: ../../
      dockerfile: src/docker/chain/Dockerfile
    depends_on:
      - aptos-builder
    image: chain
    ports:
      - 8080:8080
      - 8081:8081

  diesel:
    build:
      context: ../../
      dockerfile: src/docker/database/Dockerfile
      args:
        - DATABASE_URL=postgres://econia:econia@docker_default/econia
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=econia
      - POSTGRES_PASSWORD=econia
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
