[tool.poetry]
name = "econia-sdk"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"
packages = [{include = "econia_sdk"}]

[tool.poetry.dependencies]
python = "^3.11"
aptos-sdk = "^0.5.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
