[package]
name = 'Aptos Faucet'
version = '0.0.0'             # Per SemVer
upgrade_policy = 'compatible'

[addresses]
aptos_faucet = '0x7c36a610d1cde8853a692c057e7bd2479ba9d5eeaeceafa24f125c23d2abf942'

[dependencies.Econia]
git = 'https://github.com/econia-labs/econia'
rev = 'v4.0.3'
subdir = 'src/move/econia'
