---
name: Push API Docker image to Artifact Registry

on:
  push:
    branches: [main]
    paths:
      - src/rust

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        id: "auth"
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/153655225733/locations/global/workloadIdentityPools/github-actions-identity-pool/providers/github-actions-oidc-provider
          service_account: "github-actions-service-account@econia-0.iam.gserviceaccount.com"
          token_format: "access_token"

      - name: Log In to Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: asia-northeast1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push to Artifact Registry
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: asia-northeast1-docker.pkg.dev/econia-0/econia-backend/api:latest
          file: ./src/rust/api/Dockerfile
