---
name: Build and deploy API docs

on:
  push:
    branches:
      - main
    paths:
      - doc/api-docs/**
      - .github/workflows/deploy-api-docs.yml

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v3

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: "projects/153655225733/locations/global/workloadIdentityPools/api-docs-identity-pool/providers/api-docs-oidc-provider"
          service_account: "api-docs-service-account@econia-0.iam.gserviceaccount.com"

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6"
          bundler-cache: true
          working-directory: ./doc/api-docs/
      - run: bundle exec middleman build
        working-directory: ./doc/api-docs/

      - id: "upload-build"
        uses: "google-github-actions/upload-cloud-storage@v1"
        with:
          path: "doc/api-docs/build"
          destination: "docs.econia.exchange"
          parent: false
